# Generated by Django 4.0.1 on 2022-01-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_remove_guest_is_child_remove_party_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='display_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
