# Generated by Django 4.0.1 on 2022-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_party_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('none', 'none')], max_length=20, null=True),
        ),
    ]
